
import type { Car } from './types';

export const CARS_DATA: Car[] = [
  {
    vin: '1GKS4EK04E1123456',
    make: 'Chevrolet',
    model: 'Equinox Premier',
    year: 2022,
    price: 185000,
    mileage: 15000,
    engine: '1.5L Turbo',
    transmission: 'Automática de 6 velocidades',
    drivetrain: 'AWD',
    fuelType: 'Gasolina',
    exteriorColor: 'Branco Summit',
    interiorColor: 'Preto Jet Black',
    features: ['Teto Solar Panorâmico', 'Bancos de Couro com Aquecimento', 'Sistema de Som Bose', 'Carregador Wireless', 'Alerta de Colisão Frontal'],
    imageUrl: 'https://picsum.photos/seed/equinox/800/600',
  },
  {
    vin: 'WAUZZZGE7L1098765',
    make: 'Audi',
    model: 'A3 Sedan S Line',
    year: 2023,
    price: 260000,
    mileage: 5000,
    engine: '2.0L TFSI',
    transmission: 'S-Tronic 7 velocidades',
    drivetrain: 'FWD',
    fuelType: 'Gasolina',
    exteriorColor: 'Azul Navarra',
    interiorColor: 'Cinza Rotor',
    features: ['Virtual Cockpit', 'Faróis Full LED Matrix', 'Audi Drive Select', 'Rodas de Liga Leve 18"', 'Controle de Cruzeiro Adaptativo'],
    imageUrl: 'https://picsum.photos/seed/audia3/800/600',
  },
  {
    vin: '3FA6P0HD7NR212345',
    make: 'Ford',
    model: 'Bronco Sport Wildtrak',
    year: 2023,
    price: 250000,
    mileage: 8000,
    engine: '2.0L EcoBoost',
    transmission: 'Automática de 8 velocidades',
    drivetrain: '4x4',
    fuelType: 'Gasolina',
    exteriorColor: 'Laranja Cyber',
    interiorColor: 'Preto com detalhes em azul',
    features: ['7 Modos de Terreno (G.O.A.T. Modes)', 'Teto com Pintura Bicolor', 'Sistema de Som B&O', 'Bancos em Couro com Aquecimento', 'Câmera 360°'],
    imageUrl: 'https://picsum.photos/seed/bronco/800/600',
  },
  {
    vin: 'JTJHY7AX3J5012345',
    make: 'Toyota',
    model: 'Corolla Cross XRE',
    year: 2024,
    price: 180000,
    mileage: 2000,
    engine: '2.0L Dynamic Force',
    transmission: 'Direct Shift CVT de 10 velocidades',
    drivetrain: 'FWD',
    fuelType: 'Flex',
    exteriorColor: 'Cinza Granito',
    interiorColor: 'Preto',
    features: ['Toyota Safety Sense', 'Multimídia de 9" com Apple CarPlay/Android Auto', 'Ar Condicionado Dual Zone', 'Banco do Motorista com Ajuste Elétrico', 'Chave Presencial'],
    imageUrl: 'https://picsum.photos/seed/corolla/800/600',
  },
  {
    vin: 'WBA31AY00PEX67890',
    make: 'BMW',
    model: '320i M Sport',
    year: 2023,
    price: 320000,
    mileage: 7500,
    engine: '2.0L TwinPower Turbo',
    transmission: 'Automática de 8 velocidades',
    drivetrain: 'RWD',
    fuelType: 'Flex',
    exteriorColor: 'Azul Portimao',
    interiorColor: 'Couro Vernasca Cognac',
    features: ['BMW Live Cockpit Professional', 'Driving Assistant', 'Teto Solar Elétrico', 'Pacote M Sport', 'Sistema de Som Harman Kardon'],
    imageUrl: 'https://picsum.photos/seed/bmw320i/800/600',
  },
  {
    vin: 'SJNFAAP16U2123456',
    make: 'Nissan',
    model: 'Kicks Exclusive',
    year: 2024,
    price: 145000,
    mileage: 1000,
    engine: '1.6L 16V',
    transmission: 'XTRONIC CVT',
    drivetrain: 'FWD',
    fuelType: 'Flex',
    exteriorColor: 'Vermelho Malbec',
    interiorColor: 'Couro Macchiato',
    features: ['Visão 360° Inteligente', 'Sistema de Som Bose Personal Plus', 'Nissan Safety Shield', 'Bancos Zero Gravity', 'Painel de Instrumentos Digital de 7"'],
    imageUrl: 'https://picsum.photos/seed/kicks/800/600',
  },
];
